Repository CSC207-2022F-UofT/course-project-utoronto-chess, pull requests merged in 2022-12, with the labels that each got.

#38 Updates to UserController and tests for database functionality
  chessdb.sqlite
  src/main/java/controller/database/SQLPresenter.java
  src/main/java/controller/database/UserController.java
  src/main/java/entities/user/User.java
  src/main/java/useCases/database/SQLGateway.java
  src/test/java/controller/database/UserControllerTest.java
  src/test/java/entities/user/UserTest.java
  src/test/java/useCases/database/UserInteractorTest.java
Labels: documentation

#40 Board tests
  src/main/java/useCases/board/Board.java
  src/main/java/useCases/game/Game.java
  src/test/java/useCases/board/BoardTests.java
Labels: documentation

#44 Pieces test
  src/test/java/entities/pieces/PiecesTests.java
Labels: documentation

#39 Checkmate game 0ver logic
  src/main/java/UTorontoChess.java
  src/main/java/controller/database/SQLPresenter.java
  src/main/java/controller/database/UserController.java
  src/main/java/controller/game/ChessBoardController.java
  src/main/java/entities/pieces/Pawn.java
  src/main/java/useCases/game/Game.java
  src/main/java/usecases/board/Board.java
  src/main/java/usecases/database/SQLGateway.java
  src/main/java/usecases/database/UserInteractor.java
  src/main/java/usecases/game/Game.java
  src/main/java/views/Anim.java
  src/main/java/views/ChessPanel.java
  src/main/java/views/LoginWindow.java
  src/test/java/usecases/board/BoardTests.java
  src/test/java/usecases/database/UserInteractorTest.java
Labels: enhancement

#42 Controller Tests
  src/main/java/UTorontoChess.java
  src/main/java/controller/game/ChessBoardController.java
  src/main/java/usecases/game/Game.java
  src/main/java/views/Anim.java
  src/main/java/views/ChessPanel.java
  src/test/java/controller/game/ChessBoardControllerTest.java
  src/test/java/entities/pieces/PiecesTests.java
Labels: documentation

#43 Menu
  chessdb.sqlite
  src/main/java/UTorontoChess.java
  src/main/java/controller/database/SQLPresenter.java
  src/main/java/controller/database/UserController.java
  src/main/java/controller/game/ChessBoardController.java
  src/main/java/useCases/board/Board.java
  src/main/java/useCases/database/SQLGateway.java
  src/main/java/useCases/database/UserInteractor.java
  src/main/java/useCases/game/Game.java
  src/main/java/views/ChessPanel.java
  src/main/java/views/Leaderboard.java
  src/main/java/views/LoginWindow.java
  src/main/java/views/Menu.java
  src/test/java/useCases/board/BoardTests.java
  src/test/java/useCases/database/UserInteractorTest.java
Labels: documentation

#45 Last minute cleanup to DB stuff
  chessdb.sqlite
  src/main/java/controller/database/DatabaseGateway.java
  src/main/java/controller/database/SQLPresenter.java
  src/main/java/controller/database/UserController.java
  src/main/java/controller/game/ChessBoardController.java
  src/main/java/entities/user/User.java
  src/main/java/views/LoginWindow.java
  src/test/java/controller/database/UserControllerTest.java
  src/test/java/entities/pieces/PiecesTests.java
Labels: documentation, enhancement
